In [3]:
list(range(0, 5))

[0, 1, 2, 3, 4]

In [5]:
a = 'abc'

In [6]:
a.index('b')

1

In [15]:
l, r = 1, 5

In [16]:
all_odds = [num for num in range(l, r+1) if num % 2 == 1]
print(all_odds)

[1, 3, 5]


In [19]:
import numpy as np
np.array([1, 2]) % 2

array([1, 0])

In [20]:
all_nums = np.arange(l, r+1, 1)
odds = all_nums % 2 != 0
np.sum(odds)

3

In [21]:
odds

array([ True, False,  True, False,  True])

In [22]:
all_nums = np.arange(l, r+1, 1)

In [23]:
all_nums

array([1, 2, 3, 4, 5])

In [24]:
li = [[1,3],[2,6],[8,10],[15,18]]

In [28]:
li

[[1, 3], [2, 6], [8, 10], [15, 18]]

In [29]:
for l in li:
    
    print(l)

[1, 3]
[2, 6]
[8, 10]
[15, 18]
